### ISSUE TITLE
[Documentation] how does this work?

### ISSUE THREAD

**Issue by loudoweb** [hughsando/winrpi#1]
Hello,

I'm currently trying some stuff with RPI and came across your library. How does this work? Could you provide simple documentation or guidance?
I'm using Haxe.
Thanks

**Comment by hughsando** [comment]
This has been merged back into the standard toolchains that ship with hxcpp.
When you use the `-Drpi` from windows, it actually sets your target to "linux" and activates the "xcompile" define.
This, in turn, activates the section in the linux toolchain file that looks like:
```xml
   <section if="rpi">
      <path name="c:/SysGCC/Raspberry/bin/" unless="HXCPP_XCOMPILE_RPI_PATH" />
      <path name="${HXCPP_XCOMPILE_RPI_PATH}" if="HXCPP_XCOMPILE_RPI_PATH" />
      <set name="CXX" value="arm-linux-gnueabihf-g++" />
      <set name="HXCPP_STRIP" value="arm-linux-gnueabihf-strip" />
      <set name="HXCPP_AR" value="arm-linux-gnueabihf-ar" />
      <set name="HXCPP_RANLIB" value="arm-linux-gnueabihf-ranlib" />
   </section>
```
As well as setting the default output directory to 'rpi'
You can override the HXCPP_XCOMPILE_RPI_PATH, but installing the win-rpi cross-compile toolchain in `c:/SysGCC` location shown here is probably easiest.

This builds the exes on the windows box, and then I usually use a network drive to copy the files to the device.  If you want graphics etc, NME supports the rpi target, but other systems may need some tweaking.

**Comment by loudoweb** [comment]
Thank you for your answer!
I'll try first with NME then.
